name: wiseNkap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2002

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2


  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  provider: ^6.0.5
  table_calendar: ^3.1.0

  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/wiseNkap.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Wallet.png
    - assets/wiseNkap.png
    - assets/avatar.png
    - assets/goals.png
    - assets/analysis.png
    - assets/budget.png
    - assets/.env
